giver = {
"I do insist.",
"Have some, please.",
"Do me the honor.",
"It is yours, truleh.",
"But I insist.",
"You are hardly having any!",
"You look a bit peckish.",
"But a body must eat, non?",
"Please, have some more.",
"There were made for you.",
"I will hear nothing of it.",
"Waste not want not.",
"Will you turn me down?",
"Justify their existence.",
"Do not look a gift horse in the mouth!",
"These suit you divineleh!",
"Humble me.",
"I say, have some!",
"You could but say no.",
"Yours by right.",
"A present for you presently.",
"Second helpings?",
"Take it bitch!",
}

taker = {
"I cannot in decency.",
"How could I?",
"I could hardly impose.",
"Such kindness.",
"Thank you, but no, thank you.",
"You are but nature’s bounty.",
"Please reconsider.",
"I am on a diet.",
"Oh no no NO. I can’t possibleh!",
"Do believe, I am full.",
"Bursting at the seams I am.",
"I shall never go wanting.",
"How could you?",
"They are wasted on me.",
"Not to look a gift horse... but.",
"Egads, NO more!",
"I am humbled, but no.",
"By Jove, FAR too many!",
"I could but say yes.",
"I am not worthy.",
"You shouldn’t have, truleh.",
"I’ve had plenty.",
"Give it to me, YEAH!",
}
